FROM jekyll/jekyll

RUN \
  mkdir -p /tmp/docs && \
  git init && \
  git remote add origin https://www.github.com/docker/docker.github.io && \
  git fetch origin master && \
  GIT_WORK_TREE=/tmp/docs git checkout -f FETCH_HEAD && \
  rm -rf .git

WORKDIR /tmp/docs

# nokogiri deps
RUN apk add --no-cache ruby-dev build-base zlib-dev && \
  bundle install

RUN chmod -R 777 . && bundle exec jekyll build

CMD bundle exec jekyll serve
